name: Data Pipeline Validation
on:
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest 

    steps:
      - name: Descargar código
        uses: actions/checkout@v4 

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Instalar dependencias
        run: |
          pip install duckdb faker pandas 

      - name:  Ejecutar Pipeline de Datos
        run: python data/generate_data.py 
